### ISSUE TITLE
how can i use it in html file

### ISSUE THREAD

**Issue by jing2si** [mrmlnc/vscode-autoprefixer#7]
**how can i use it in html file**

**Comment by mrmlnc** [comment]
Hello @jing2si,

Unfortunately, right now it's impossible, because VS Code does not support nested languages. In August, the team will work on that (see https://github.com/Microsoft/vscode/issues/8928). Estimated date to 10 September in the stable release. As soon as the developers will add this capability - you can use it with this plugin in the Insiders releases.

**Comment by mrmlnc** [comment]
I close this issue as his solution does not depend on me.
